### ISSUE TITLE
Improve array syntax

### ISSUE THREAD

**Issue by Athas** [HIPERFIT/futhark#179]
At present, the type for an NxM array of integers is `[[int,M],N]`.  It is kind of annoying that you have to read it right-to-left to get the natural shape.  One solution is to instead use an `[N,[M,int]]` notation, but maybe someone can come up with something better.

**Comment by Athas** [comment]
We might also want to improve the function/parameter declaration syntax while we're messing around.  It seems that most languages have agreed that having the result type at the end makes the most sense (Rust, Go, etc).  So for example, the factorial function would be:

```
fun fact(n : int) -> int = ...
```

This also fits well with usual type ascription notation.  (The arrow is from Rust - we could use colon instead.)

**Comment by MikkelStorgaard** [comment]
On Thu, May 19, 2016 at 9:27 AM, Troels Henriksen
<notifications@github.com> wrote:
>
> We might also want to improve the function/parameter declaration syntax while we're messing around. It seems that most languages have agreed that having the result type at the end makes the most sense (Rust, Go, etc). So for example, the factorial function would be:
>
> fun fact(n : int) -> int = ...
>
> This also fits well with usual type ascription notation. (The arrow is from Rust - we could use colon instead.)
>

I am against putting more information between the function arguments
and the expression side of the functions, but that might just be by
habit.

**Comment by Munksgaard** [comment]
> I am against putting more information between the function arguments and the expression side of the functions, but that might just be by habit.

I like the Rust-like notation. But that might also be out of habit :)

**Comment by Munksgaard** [comment]
> At present, the type for an NxM array of integers is [[int,M],N]. It is kind of annoying that you have to read it right-to-left to get the natural shape. One solution is to instead use an [N,[M,int]] notation, but maybe someone can come up with something better.

Another option is the C-like `int [M, N]`.

**Comment by Athas** [comment]
What would that look like without the annotations?  int [,]?

-- 
\  Troels
/\ Henriksen

**Comment by Munksgaard** [comment]
I guess so. You'd have `int []`, `int [N]`, `int [,]`, `int [M, N]`, and so on. 
I cant decide if `int [,]` really is uglier than `[[int]]`, or if I'm just more used to the latter.

**Comment by Athas** [comment]
It is definitely uglier.

-- 
\  Troels
/\ Henriksen

**Comment by melsman** [comment]
... I'm all for colons for return types and the [N,[M,int]] notation for
multidimensional arrays, which emphasises that the SOACs work in a
"structural fashion"...

On Thu, May 19, 2016 at 11:12 AM, Troels Henriksen <notifications@github.com

**Comment by Athas** [comment]
Cosmin proposed using asterisk instead of comma, i.e., `[N*[M*int]]`.  Makes sense to me.  Thoughts?

**Comment by MikkelStorgaard** [comment]
On Thu, Jun 2, 2016 at 4:47 PM, Troels Henriksen <notifications@github.com>
wrote:

> Cosmin proposed using asterisk instead of comma, i.e., [N*[M*int]]. Makes
> sense to me. Thoughts?
>
> —
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub
> <https://github.com/HIPERFIT/futhark/issues/179#issuecomment-223315073>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/ADfkWduvig5OtQ_-C3kiS2omEGvkHV2zks5qHu0bgaJpZM4Id_Oh>
> .
>
As long as it does not clash with the uniqueness-operator.

**Comment by Athas** [comment]
It does not, except visually.  I don't think it's a big problem.

-- 
\  Troels
/\ Henriksen

**Comment by melsman** [comment]
Fritz has some interesting comments on the syntax; go chat with him also...

Den torsdag den 2. juni 2016 skrev Troels Henriksen <
notifications@github.com>:

**Comment by henglein** [comment]
(1) It turns out the isomorphism theory of simple types is high-school
algebra, the algebra of calculating with +, * and exponent.  Arrays are
(certain) exponentials; pairs, triples are products; and sum types (such as
Booleans) are sums.

What does this have to do with Futhark?

Using a familiar notation to notationally support these isomorphisms should
be useful because then the types and their natural (both
category-theoretically, intuitively and compiler-optimization-wise)
transformations look like familiar algebraic rewritings.  (2) Also, there
are some general (concrete syntax) usability concerns to take into account,
I believe.

ad 1. Isomorphisms.

Some high-school algebra equalities (where I'm using, ominously, 'int' as a
variable name instead of 'x')

int^5 = int * int * int * int * int
(int^5)^3= (int^5)*(int^5)*(int^5) = int * ... * int (15 times)
int + int = 2 * int

These are not equalities, but natural isomorphisms on simple set (= sets
denoted by the types):
* is Cartesian product, + is disjoint union, ^ is the full function space.
 5 is a five-element set, canonically iota(5); think of
5 implicitly as standing for iota(5) whenever a type is required.  The
correspondence with high-school algebra (a term by Tarski, by the way) and
its interpretation on natural numbers is by taking the cardinality of the
sets involved. The type of n-element arrays of elements of type t
corresponds to the exponential  t^n.

ad 2. The ^ notation for exponential is terrible for one reason and
inconsistent for another:
Firstly (the terrible part; subjective, but I believe consistent with
findings on UX of concrete programming language syntax in the 80s), it is
graphically (read: its visual rendering in the 2 dimensions of the
Euclidean space you're presently looking at) symmetric in one dimension;
that is, flipping it along a vertical line through its middle yields the
symbol itself.  This suggests that flipping "x ^ y" along the same line
should be the same as "y ^ x", in other words, the symbol's symmetry
suggests that the operation is algebraically symmetric; which it isn't.
 (It not unusual to use symmetric infix operators for nonsymmetric
operations, but I believe it's, all things equal, better to signal visually
that something is not symmetric rather than using a symmetric graphic and
reminding the reader to ignore its visual symmetry.)
Secondly, the exponent comes last (to the right), which is okay by itself
(who says the exponent is less or more important than the base?), but
inconsistent with writing 2 * int instead of int * 2. Note that ^ is to *,
as * is to +, and as + is to 1, not just intuitively, but by the levels of
the Gregorczyk Hierarchy: the left operation is defined in terms of one
level of primitive recursion using the right operation.  So if 2 * int is
preferred then this suggests the exponent should come first, not the base.

Indeed in logic, type theory and functional programming  we are accustomed
to just such a notation for exponent where the exponent comes first:  we
write int -> real instead of real^int, with the exponent int coming first,
consistent with the 2 in 2 * int coming first.  In terms of high school
algebra we'd be writing 5 -> int = int * int * int * int * int.
Programming languages usually disguise notationally that array types are
subsets of function spaces, for some reason that I suspect has only a
historically sane account: for function types we write the exponent first
(the arrow notation), and for
array types we write the basis first, where for confusing measure the
declared variable might be spliced in.  This started with ALGOL 60; e.g.
"integer array A[start:end]"; which corresponds to A: [start...end] ->
integer, respectively integer^[start...end] in the two notations above.

My input:

   - Don't use * instead of "," for something that is not symmetric -- by
   that measure, "," is better (it's not graphically symmetric).  The reason
   for using * is supposedly that it visually supports the isomorphism of
    [N*[M*int]] and [(N*M)*int].  But using * (which suggests the intent to
   look like \times, by analogy with * used for multiplication of numbers in
   most programming languages) for exponentiation is questionable: it suggests
   that + should be used for (Cartesian) product (!); sum types being out of
   favor in Futhark doesn't free -- in user's minds --  the product symbol
   from serving as an exponentiation operator.
   - Don't use "," -- it suggests a pair (by strong convention) or at least
   something associative, being an infix operator (Many operators in real
   life, notably juxtaposition for function application, violate the
   'graphically-infix-thus-associative' principle, with some cumbersome
   consequences.)
   - Stick either with convention where the order of base and exponent in
   function types and in array types is *not* the same, but then do stick with
   convention:
      - use int[N][M], int[N*N] or such for arrays (a bit tricky to signal
      the difference between a multidimensional array and its canonical
      linearization by multiplying out the ranks); or
      - use the same order as function space constructor '->' if
      introducing a new/uncommon notation to support the readers's adoption of
      new syntax by semantically correct association with something familiar;
      e.g. [M] int, where this is parsed (in the sense of 'semantically
      decomposed') as [M] followed by int; so juxtaposition is the array type
      constructor, the brackets belong with the M, where [M] denotes
iota(M) as a
      type. One thus gets types such as [M] [N] int, ([M] * [N]) int
and [M * N]
      int, all pairwise different, but isomorphic, where "*" is used
as Cartesian
      product constructor (which is better than using "( , )" since
the Cartesian
      product is, well, a product and not a pair, and one might as well use a
      symbol that is reminiscent of products rather than pairs).

Fritz

**Comment by Athas** [comment]
`int [M] [N]` is the closest contender I've seen, but it's not particularly pleasant when the dimensions are not known (or implied).  `int [][]`?  Or maybe `int[?][?]`?

**Comment by Athas** [comment]
I have switched the notation used in the *core* language prettyprinter to the one Fritz suggested.  That will give me a chance to read a bunch of code using it, which seems a good a way as any to get an idea of whether it will work.  Looks good so far.  This is a short example:

```
entry {i32} main() =
  let {bool[9i32] reshape_9369} = [True, True, True, True, False, False, False,
                                   True, False]
  let {bool[1i32][9i32] reshape_9370} = replicate(1i32, reshape_9369)
  -- reshape_9371 aliases reshape_9370
  let {bool[9i32] reshape_9371} = reshape((9i32), reshape_9370)
  let {bool[21i32] concat_x_9372} = replicate(21i32, False)
  let {bool[30i32] res_9373} = concat(concat_x_9372, reshape_9371)
  -- reshape_9374 aliases res_9373
  let {bool[10i32][3i32] reshape_9374} = reshape((10i32, 3i32), res_9373)
  -- rearrange_9375 aliases reshape_9374
  let {bool[3i32][10i32] rearrange_9375} = rearrange((1, 0), reshape_9374)
  -- reshape_9376 aliases rearrange_9375
  let {bool[30i32] reshape_9376} = reshape((30i32), rearrange_9375)
  let {bool[70i32] concat_x_9377} = replicate(70i32, False)
  let {bool[100i32] res_9378} = concat(concat_x_9377, reshape_9376)
  -- reshape_9379 aliases res_9378
  let {bool[10i32][10i32] reshape_9379} = reshape((10i32, 10i32), res_9378)
  -- rearrange_9380 aliases reshape_9379
  let {bool[10i32][10i32] rearrange_9380} = rearrange((1, 0), reshape_9379)
  let {i32[10i32] map_arr_9381} = iota(10i32, 0i32, 1i32)
  let {bool[10i32][10i32] rearrange_9391} =
    map(10i32,
        fn {bool[10i32]} (i32 x_9387) =>
          let {i32 x_9388} = add32(x_9387, 3i32)
          let {i32 i_9389} = smod32(x_9388, 10i32)
          -- res_9390 aliases rearrange_9380
          let {bool[10i32] res_9390} = rearrange_9380[i_9389]
          in {res_9390},
        map_arr_9381)
...
```

**Comment by Athas** [comment]
I particularly like that there is still a nice property of composition.  For any `t`, you can get an array of `t`s by writing `t[N]` (or just `t[]`?).

**Comment by Athas** [comment]
I just realised that the correct rule is more complicated.  You create an array of `t ds` (where `ds` is a sequence of dimension specifiers) by saing `t [N]ds`.  Drat.  I really liked the easy composition.  One solution (if this is even a problem) is to write the dimensions to the *left* of the element type, i.e., `[N][M]int`.

**Comment by Athas** [comment]
I have been playing around with the `[N][M]int` notation in the core language.  It's not so bad once you get used to it.  Cosmin suggested using commas instead, so that it would be `[N,M]int`, which is less typing.  I'm not sure how much more time we should spend on this.  One one hand, arrays are *the* data structure in Futhark.  On the other hand, is the difference between these different left-to-right notations really so significant?  I currently consider these possibilities:

  * a0) `[N][M][K]int`

  * a1) `int[N][M][K]`

  * b0) `[N,M,K]int`

  * b1) `int[N,M,K]`

  * c0) `[N*M*K]int`

  * c1) `int[N*M*K]`

I don't think I have seen any other convincing suggestions.  I am partial to a0 (or its slightly simplified b0 variant), because I like how it mirrors the structure when read left to right (and at the bottom is a scalar).

**Comment by melsman** [comment]
I think there is some benefit from being able to write up the type of most
of the SOACs in a collective fashion using a0 and a1. With a0, the type of
map (or rather, map1) can be expressed as follows:

 map1 : ('a -> 'b) -> [N]'a -> [N]'b

Using the other suggestions, the type of the individual SOACs cannot easily
be expressed...

**Comment by Athas** [comment]
This is also my main concern.  But, really, how much difference is it in
practice?

-- 
\  Troels
/\ Henriksen

**Comment by melsman** [comment]
When we get modules with polymorphic function entries, it could become
quite useful!

>

**Comment by Athas** [comment]
I guess we could support `[N,M,K]t` as a shortcut syntax for `[N][M][K]`
and get the best of both worlds.

-- 
\  Troels
/\ Henriksen

**Comment by melsman** [comment]
Yes, that is a possibility... What should be the syntax for arrays of
unknown size? Can one write [M[][P]int and [M,,P]int?

Den søndag den 5. juni 2016 skrev Troels Henriksen <notifications@github.com

**Comment by Athas** [comment]
`[M][][P]int`, yes.  And I suppose the shorthand would permit `[M,,P]int`.  Not beautiful, but not terribly bad.  In practice, I expect that users will tend to define all dimensions or none, and `[][][]int` doesn't look *that* bad, I suppose.  It's even easier to read at a glance than the current notation of `[[[int]]]`!

**Comment by Athas** [comment]
I have made this change in branch new-array-syntax.  I used the following program to convert the test suite - you can use it too!

```
import qualified Data.ByteString.Char8 as BS
import Data.Char
import Data.List
import System.Environment
import Text.ParserCombinators.ReadP

main :: IO ()
main = do [file] <- getArgs
          s <- BS.readFile file
          BS.writeFile file $ BS.pack $ correct $ BS.unpack s

correct :: String -> String
correct [] = []
correct (c:'[':cs)
  | not $ isAlphaNum c, not $ c `elem` "'_", -- Hack to avoid indexing.
    [(t,cs')] <- readP_to_S parseArrayType ('[':cs) =
      c : ppType t ++ correct cs'
correct (c:cs) =
  c : correct cs

data Type = Array Type (Maybe String)
          | Tuple [Type]
          | Type String
          deriving (Show)

ppType :: Type -> String
ppType (Type s) = s
ppType (Tuple ts) = "(" ++ intercalate "," (map ppType ts) ++ ")"
ppType (Array t Nothing) = "[]" ++ ppType t
ppType (Array t (Just d)) = "[" ++ d ++ "]" ++ ppType t

parseArrayType, parseType, parseTupleType, parseBottomType :: ReadP Type
parseType = choice [parseArrayType, parseTupleType, parseBottomType]
parseArrayType = brackets $ Array <$> parseType <*> option Nothing (Just <$> parseDimDecl)
parseTupleType = parens $ Tuple <$> parseType `sepBy1` symbol ','
-- Hack: a bottom type must be more than one character, to avoid
-- catching array indexing (often [i] or [j]).
parseBottomType = lexeme $ Type <$> ((:) <$> satisfy isAlpha <*> many1 (satisfy isAlphaNum))

parseDimDecl :: ReadP String
parseDimDecl = symbol ',' >> lexeme (many1 (satisfy (\c -> isAlphaNum c || c == '_')))

lexeme :: ReadP a -> ReadP a
lexeme p = skipSpaces >> p

symbol :: Char -> ReadP Char
symbol = lexeme . char

brackets, parens :: ReadP a -> ReadP a
brackets = between (symbol '[') (symbol ']')
parens = between (symbol '(') (symbol ')')
```

Will merge this soon unless someone is seriously unhappy with the new syntax.
