### ISSUE TITLE
Add a way to put negative run-time tests in the test suite

### ISSUE THREAD

**Issue by Athas** [HIPERFIT/futhark#22]
You can already make tests that are expected to fail at compile-time by having neither `.in` nor `.out` files.  A test expected to fail at runtime could have an `.in`, but no `.out` file.

Of course, it would also be nice to be able to specify the expected failure.  In a perfect world, it would also be nice to embed this information in the test program itself, and not in separate files.

But this is not a perfect world (well, maybe it will be when Maya is done).

**Comment by Tayacan** [comment]
On 5 March 2015 at 08:45, Troels Henriksen <notifications@github.com> wrote:
>
> You can already make tests that are expected to fail at compile-time by
having neither .in nor .out files. A test expected to fail at runtime could
have an .in, but no .out file.
>
> Of course, it would also be nice to be able to specify the expected
failure. In a perfect world, it would also be nice to embed this
information in the test program itself, and not in separate files.
>
> But this is not a perfect world (well, maybe it will be when Maya is
done).

It won't be. Vidar does not care what happens when you run the program, so
you won't be able to use it for runtime failures.

--
- Maya

**Comment by Athas** [comment]
Right, but we'll have to parse program comments to power Vidar anyway, so at that time half the work will already be done.  Input/output data sets will just be another bunch of magical comments.
