### ISSUE TITLE
OpenCL error on large input to simple reduce program

### ISSUE THREAD

**Issue by RasmusWL** [HIPERFIT/futhark#236]
Just ran into an error using a large input (2 GB), with a simple sum program defined in `i32-reduce.fut`:
```
fun main (xs : []i32): i32 =
    reduce (+) 0 xs
```

```
$ futhark-dataset --generate=[$(python -c 'print(2**29)')]i32 > /tmp/i32-2pow29.dat
$ futhark-opencl i32-reduce.fut
$ ./i32-reduce -s < /tmp/i32-2pow29.dat
Using platform: NVIDIA CUDA
Using device: GeForce GTX 780 Ti
Setting lockstep width to: 32
Created kernel kernel_64.
Created kernel kernel_90.
Launching kernel_64 with global work size [32768].
./i32-reduce: i32-reduce.c:1580: OpenCL call
  clFinish(fut_cl_queue)
failed with error code -36 (Invalid command queue)
```

ps. the `/tmp/i32-2pow29.dat` file is already present on GPU03

**Comment by Athas** [comment]
I don't think a single 2GiB array will fit in memory on the GTX 780s,
possibly due to fragmentation effects.  Note that OpenCL allocates
memory lazily, so while the clCreateBuffer() call may seem to work, the
actual allocation does not take place until the kernel that uses the
buffer is launched, whereupon it will fail.

-- 
\  Troels
/\ Henriksen

**Comment by RasmusWL** [comment]
So futhark simply doesn't support working on that amount of data?

**Comment by Athas** [comment]
No.  Peak working set has to fit.  Streaming data in and out is future work.  Works on `napoleon`.

**Comment by tomberek** [comment]
Streaming data update?

**Comment by athas** [comment]
Sorry, not yet.  The best idea we've come up with is to manually chunk from the outside, and only call the Futhark program with a subset of the full data at a time.
