### ISSUE TITLE
Emacs mode freezes emacs on specific comment line

### ISSUE THREAD

**Issue by ahovgaard** [HIPERFIT/futhark#257]
I know this sounds ridiculous, but emacs freezes upon inputting or opening a file containing this specific line comment:

```haskell
-- Given two pairs of type (i32, i32), returns the pair with the maximum
-- value in the first position.
```

This problem has even been reproduced on another machine.

**Comment by nqpz** [comment]
Thanks for reporting this.  This was a fun Emacs Lisp bug.  I have fixed it.

The bug was in the syntax highlighter, specifically the part that highlights type alias declarations like this one:

```
type custom_type = some_existing_type
```

The Emacs Lisp code tried to highlight both `custom_type` and `some_existing_type`.  It did this with overlapping regular expressions: The first regexp would match on `custom_type` in the type alias declaration context, and the second regexp would match on `some_existing_type` in the *same* context, i.e. the start of the second regexp was the same as the start of the first regexp.

This was an easy way to ensure that `some_existing_type` only got highlighted when it was located in a type declaration, but unfortunately this seems to cause your bug.

The problem in your comment is that it contains the substring `type (i32, i32)`.  Emacs somehow applies the highlighting regexpes to the comment line, and somehow freezes.  The problem went away once I removed the regexp overlap, though I'm not quite sure why.  Maybe I should read the documentation...
