### ISSUE TITLE
mod or module?

### ISSUE THREAD

**Issue by Athas** [HIPERFIT/futhark#288]
In Rust, modules are defined with `mod`, not `module`.  Since we steal so much of Rust's lexical syntax anyway...

Thoughts?

**Comment by nqpz** [comment]
I like `module` better than `mod`, because it is a real word.  However, I like e.g. `f32` better than `float32`, because it is shorter, so my thinking is inconsistent.

I have one argument in favour of keeping `module`: If `module` is changed to `mod`, why not also change `include` to `inc`, `default` to `def`, and so on for other keywords?

**Comment by Athas** [comment]
I had not considered changing 'include' to 'inc', and I think it looks
weird.  Maybe I am wrong?  We do have 'fun' instead of 'function',
though.  I imagine that 'module' is used much more often than 'include',
which is why a shortening may be justified.  (And of course, 'fun' and
'val' are used much more again.)

'default' can be whatever; I'd prefer to get rid of that eventually
(once we get proper type inference).  But 'default' is probably the most
rarely used keyword of them all.

-- 
\  Troels
/\ Henriksen

**Comment by RasmusWL** [comment]
I guess I would be in favour of `module` as well. But as Niels I do not have consistent thinking.

Maybe I am just getting old and don't like change :D

**Comment by Athas** [comment]
Martin pointed out that no other keyword in the module language is abbreviated.  For consistency, `module` remains `module`.
