### ISSUE TITLE
Permit underscores as non-semantic separators in numeric constants

### ISSUE THREAD

**Issue by Athas** [HIPERFIT/futhark#292]
So we can write 0xFF_FF_FF_FF instead of 0xFFFFFFFF, or 1_000_000 instead of 1000000.  Many languages seem to permit this nowadays.  They have no semantic significance.

**Comment by Athas** [comment]
I'll leave this one open for a while to see if anyone wants to get their feet wet.  It's very simple to implement, I think - just a modification of the [lexer](https://github.com/HIPERFIT/futhark/blob/master/src/Language/Futhark/Parser/Lexer.x).  The implementation involves extending the regular expressions for numeric constants, followed by filtering away the underscores before interpreting the number.

**Comment by samrat** [comment]
Hi, I am attempting to implement this feature. The changes to the lexer are simple enough and seem to be working. But one thing not discussed here is that if *compiled programs* are to accept numeric literals with underscores, changes will also need to be made into `reader.py` and `reader.h`. 

The change to `reader.py` is trivial but because `reader.h` uses `scanf` to read input, to support literals with underscores we will need to replace `scanf` with a function of our own(something similar to `parse_int` in the Python reader).

I do want to continue work on this issue to make the change to `reader.h`. Just wanted to give you a heads-up on how I plan to proceed.

**Comment by Athas** [comment]
Right, I had forgotten about those. Good that you are working on this!

**Comment by Athas** [comment]
I little advice I thought of:

  * Remember to update the grammar in the language reference: https://github.com/HIPERFIT/futhark/blob/master/docs/language-reference.rst

  * Take care that numbers consisting entirely of underscores are not permitted.  An easy way to accomplish this may be to require that the first character is not an underscore.

Maybe it's OK to support multiple consecutive underscores.  Maybe it's useful for finer subdivision, e.g. for a binary literal: 0b1010_1010__1010_1010__1010_1010__1010_1010__1010_1010.  Your call.  Some languages don't permit this, others do.

**Comment by samrat** [comment]
Thanks! I will make sure to update the language reference before I send in a pull request.

I have changed the lexing rule to require the first character is not an underscore character.

**Comment by Athas** [comment]
Closed in fc5820aca8096cc77b73042e907103fd81ddaedc.
