### ISSUE TITLE
Python/numpy API behaves in unexpected ways

### ISSUE THREAD

**Issue by pouyatafti** [HIPERFIT/futhark#310]
Have a look at this:

Here's a simple matrix product in Futhark (A*B^T):
```
 entry matProduct (mat1: [Is][Js]f32) (mat2: [Ks][Js]f32): [Is][Ks]f32 =
     map (\row1 -> map (\col2 -> reduce (+) 0f32 (map (*) row1 col2) ) mat2) mat1
```

And here are two funny matrices (numpy arrays):
```
A = np.array([[1,2],[4,8],[16,32]], dtype="float32")
B = np.array([[0,1,3,7],[15,31,63,127]], dtype="float32")
```
with their product:
```
A.dot(B)

    array([[   30.,    63.,   129.,   261.],
           [  120.,   252.,   516.,  1044.],
           [  480.,  1008.,  2064.,  4176.]], dtype=float32)
```

So far so good.  However, now compare the following:
```
matProduct(M, X.T)

    array([[    2.,    17.,    77.,   317.],
           [    8.,    68.,   308.,  1268.],
           [   32.,   272.,  1232.,  5072.]], dtype=float32)

matProduct(M, X.T.copy())

    array([[   30.,    63.,   129.,   261.],
           [  120.,   252.,   516.,  1044.],
           [  480.,  1008.,  2064.,  4176.]], dtype=float32)
```

!!!

I can imagine how/why this is happening, but it's confusing nonetheless.

**Comment by Athas** [comment]
It is because Futhark retrieves the underlying data instead of the transposed view?  Nice catch!  I'm actually not that proficient in Python or Numpy, so do you have a suggestion on the nicest way to resolve this?

I assume you are using the PyOpenCL backend?  In that case, we simply use a `pyopencl.enqueue_copy` to copy from the Numpy array into the PyOpenCL memory buffer.  A quick solution, if slightly inefficient, is to call `.copy()` on all Numpy arrays that have a nonstandard view (are transposed, for example), before we copy them.

**Comment by pouyatafti** [comment]
Thanks for the quick response!  I'm indeed using the PyOpenCL backend (on the integrated Intel GPU of a 13" MBP from 2015! ;) but even there I start to see some speed-up vs numpy for bigger matrices).

I'm not an expert on the internals of numpy either, but calling `.copy()` on views sounds like a reasonable compromise to me.  Maybe there is a way to be more efficient by applying the transformation while copying the array to the PyOpenCL buffer, but this seems more complicated and error-prone.  This [SO answer](http://stackoverflow.com/a/11286976) appears to suggest that checking whether you are dealing with a view could be as simple as `(A.base is A) or (A.base is None)`.
