### ISSUE TITLE
Should we permit top-level definitions with 'let'?

### ISSUE THREAD

**Issue by Athas** [HIPERFIT/futhark#316]
In OCaml and F#, top-level definitions are made with `let`:

```
let pi = 3.14159265358979323846264338327950288419716939937510
let gauss x = exp(- 0.5 *. x *. x) /. sqrt(2. *. pi)
```

In Futhark, we use `val` for values and `fun` for functions.  This works OK for now, but will become confusing once we get higher-order functions, as suddenly you can define functions with `val` too.

Should we support add OCaml/F#-like `let` declarations at top-level?

**Comment by henglein** [comment]
Can "let" be elided altogether?

**Comment by Athas** [comment]
No, that would cause ambiguities.  Should

```
f x = x
g x = y
```

be seen as a definition of functions `f x = x` and `g x = y`, or a function `f x = x g` and value `x = y`?

This can be resolved by requiring declarations to be terminated with some symbol - linebreaks or semicolons, for example.  I'm not particularly interested in making Futhark whitespace-sensitive, and I don't see semicolons as more readable than `let`.

**Comment by henglein** [comment]
What happend to ";" and other punctuation?  Has programming gone the
Hemmingway?

**Comment by Athas** [comment]
Futhark is more of an e e cummings language, really.

**Comment by henglein** [comment]
e e cummings wouldn't use val, fun or let.  He'd use punctuation: blank
spaces, aka layout rules. COBOL, Haskell, Python any one?  I prefer visible
punctuation, with short and as such generally recognizable punctuation such
as ";" rather than unusual one such as "let" camouflaged as pidgin English.
(As for the latter, much can be learned from COBOL, I believe.  Then again,
I have followed research in concrete syntax usability only on an ad hoc
basis since the 80s, and there is precious little the last 20 years.)

**Comment by oleks** [comment]
There is also the option of mild white-space sensitivity, by introducing `eol` as a token.

**Comment by Athas** [comment]
Such that every declaration must be `eol`-terminated?  It's an interesting idea, but very awkward to express in the grammar, as we must now permit `eol` between terms.  This is the reason we use lexers in the first place.

**Comment by henglein** [comment]
Oleks is rarely, but evidently not never, in a humorous mood!?
