### ISSUE TITLE
Enable Rasmus's segmented reductions

### ISSUE THREAD

**Issue by Athas** [HIPERFIT/futhark#322]
The segmented reductions done by @RasmusWL can handle our entire test suite and all benchmarks without performance regressions.  In several cases, performance improves appreciably.  So, why are they not enabled by default?

**Comment by RasmusWL** [comment]
There is a single case that I want to be able to handle, and I should be able to loot at this over the weekend :)

**Comment by Athas** [comment]
So how come all the tests pass if there's a known defect?

**Comment by Athas** [comment]
(I'm handing in a report next week where your work makes the difference between x80 and x130 speedup, which is why I'm a little antsy get it in.)

**Comment by RasmusWL** [comment]
I suspect the reason you don't see any problems, is that you're only looking at using my implementation for segmented reductions. If you turn on `versionedCode`, my implementation will also be used for segmented redomaps, and there are some cases that are not handled properly. 

On example of an example that is not handled properly is [tests/segredomap/ex3.fut](https://github.com/HIPERFIT/futhark/blob/d25a6b828a62c6ff7445c42b48e00e84affa9805/tests/segredomap/ex3.fut). Currently such programs are held back by some very crude assumptions I made early on, that turns out to be wrong. [example here](https://github.com/HIPERFIT/futhark/blob/d25a6b828a62c6ff7445c42b48e00e84affa9805/src/Futhark/Pass/ExtractKernels/Segmented.hs#L81)

I ran out of time today to work on Futhark, and I'm going on vacation for the next week. I will come back and fix this, but for now "here be dragons".

If you still want your speedup, there should be no problem enabling it for only **segmented reductions** :)
