### ISSUE TITLE
Float test passes when it shouldn't

### ISSUE THREAD

**Issue by samrat** [HIPERFIT/futhark#342]
I think I may have run into a bug. This test passes, but shouldn't:

```
-- ==
-- input {
-- [456123.789678, -123456.314]
-- }
-- output {
-- [456123.789678, -123456.314]
-- }

let main (b: []f64): []f64 =
     map (\(i: f64): f64 -> i + 5.1f64) b
```

I haven't looked too deeply into how the tests are run so I may be missing something.

**Comment by Athas** [comment]
Pretty sure this is because `futhark-test` uses a tolerance of 0.2% when comparing floating-point numbers:  See the code at https://github.com/HIPERFIT/futhark/blob/master/src/Futhark/Test/Values.hs#L357 (in particular the definition of `minTolerance`).

This is a tricky problem, since many real benchmarks are in practice (when run on GPUs) not accurate to more than that tolerance, IIRC.

**Comment by samrat** [comment]
Ah, thanks. I will close this issue.

**Comment by Athas** [comment]
If necessary, `futhark-test` could support an annotation giving the desired tolerance for a given benchmark (or even data set).
