### ISSUE TITLE
Support for images/textures

### ISSUE THREAD

**Issue by hermestobias** [HIPERFIT/futhark#353]
Are there any plans to support images/textures on the GPU, with hardware based linear filtering, edge clamping, etc?

**Comment by Athas** [comment]
Unfortunately not.  Since Futhark is a platform-agnostic high-level language, GPU features are not directly exposed.  GPUs just happen to be the most interesting platform currently targeted by the compiler.

It might be possible to come up with a high-level model that can also be translated to something reasonable on non-GPUs, but I'm not quite sure what it would look like.  Maybe an abstract data type that is somehow specially recognised by the compiler, and turned into texture memory if the backend supports it...

**Comment by hermestobias** [comment]
I was envisioning something like functions sample2D, sample3D, etc that takes an array, a floating point tuple index and a "sampler descriptor" record (filter mode, edge mode, etc). This could be emulated on CPUs (like how OpenCL does it), but on GPU it would cause the array to be materialized as a texture instead of a buffer (or copied into such if used as both).

The built in linear sampling is one thing (its part of the die that now goes unutilized), but the biggest issue is the cached uncoalesced access that textures provide. How would you e.g. write a futhark program that rotates an image an arbitrary amount of degrees efficiently?

**Comment by hermestobias** [comment]
Thanks for your reply, much appreciated! I hope you'll be able to find a solution that fits other design requirements in the future.
