### ISSUE TITLE
Manually setting the stride of ranges gives strange behaviour

### ISSUE THREAD

**Issue by Qata** [HIPERFIT/futhark#374]
`[n...0]` correctly produces `empty(i32)` for positive values.
`[n..(1)...0]` causes a floating point exception when passed `1` as input and produces `[ni32, 1i32]` for any other positive input.
`[n..(-1)...0]` produces `[ni32]` for positive input.

**Comment by Athas** [comment]
I think this is all correct behaviour.  The `..(1)`/`..(-1)` part is not a *stride*, but an example of the second element of the sequence.  Thus, `[n..(1)...0]` means "first element is `n`, second is `1`, down to `0`".  The stride is implied by the difference between the first and the second element (and some kind of error if this stride is zero is expected behaviour, although an FP exception is probably not the right way to do it).

**Comment by Qata** [comment]
Oh whoops, my misunderstanding.

**Comment by Athas** [comment]
Of course, this may be bad language design.  An explicit stride may be better.

**Comment by Qata** [comment]
Yeah I think so, knowing the value of the element is necessary for the current implementation, which hampers its use cases. Should I open an issue discussing its change to a stride?

**Comment by Athas** [comment]
Yes please.
