### ISSUE TITLE
The second value element in ranges should instead be a stride

### ISSUE THREAD

**Issue by Qata** [HIPERFIT/futhark#375]
The current functionality (`[first..second...last]`) hampers the use of the range operators in generic circumstances, since the second element is needed in order to set the stride.

Instead I propose that we change this to be `[first..stride...last]`.

**Comment by Athas** [comment]
We should consider what is most readable in various cases.  For example, with constants, with the current semantics on the left, and the proposed new one on the right.

* `[1..2...10]` or `[1..1...10]`
* `[1..3...10]` or `[1..2...10]`
* `[10..9...1]` or `[10..-1...1]`

And with variables:

* `[i..i+1...j]` or `[i..1...j]`
* `[i..i+2...j]` or `[i..2..j]`
* `[j..j-1...i]` or `[j..-1...i]`

I'm not really sure which is best or most consistent.  In most languages that have the example-based syntax, comma is used, which is an argument that we should *not* do that, since we don't use the comma.

On the other hand, if we move to explicit strides, then the semantics become *a lot* like our array slicing, which uses `[start:end:stride]` (like Python!).  Maybe we should just use that everywhere, then.

**Comment by Qata** [comment]
For some reason it hadn't even occurred to me at all that you can just do `[i..i+1...j]`, major brain melt on my part. My support for my own suggestion just wavered a lot.

**Comment by Qata** [comment]
Yep after doing some tests I'm totally fine with the existing syntax. Please ignore.
