### ISSUE TITLE
Specify compiler pipeline for futhark-test

### ISSUE THREAD

**Issue by RasmusWL** [HIPERFIT/futhark#51]
For me it would be handy to be able to add `-s --flattening` to test if flattening actually does work :)

**Comment by Athas** [comment]
So would this apply to every test being done (type-checking, interpretation, compiled code generation)?

**Comment by Athas** [comment]
Also, when would this new stage be inserted?  The full pipeline is quite long.  And actually, for `futhark-c` and friends it is by design not possible to change the pipeline at all...

**Comment by RasmusWL** [comment]
As long as it works with `-t`, `-i`, and `--run`, I would be happy :)

**Comment by Athas** [comment]
But where in the pipeline?  Why not just modify the futhark-c pipeline to run this pass in your branch?

**Comment by Athas** [comment]
These are the constraints: `futhark-i`, `futhark-c`, `futhark-opencl` and others we make in the future do not suppport modification of the compiler pipeline, possibly with the exception of disabling optimisation.  They are intended as concrete demonstrations of the compilation technique and are very rigid in order to avoid some problems with some compiler research (which I will freely rant more about if necessary).  `futhark-test` must at least in some mode run these programs or else it is not really an integration test.

What we can do: add a new flag to `futhark-test` that allows one to specify an entire new command to run for a test program.  For example, we can imagine `futhark-test --compiler=futhark-flatten`, where `futhark-flatten` is some shell script that calls `futhark` and `gcc` as appropriate.  This should be sufficient for testing transformations before they make it into the main pipeline (which is the intended destination of your flattening work), whilst not doing violence on the overall design in the meantime.

**Comment by RasmusWL** [comment]
Why not a `futhark-test [-i|-t|--run] --pipeline="-s --flattening"` which simply runs `futhark` with this specific pipeline?

**Comment by Athas** [comment]
If you want to actually generate code, `-s` is only half the story - after that comes sequentialisation, adding allocations, optimising said allocations, and then deciding on a backend.  This is why it is in general not easy to decide when and where to insert an extra pass.  Besides, I really want `futhark-test` to use the "end-user compilers", at least in its default configuration.  Perhaps a special "custom" test action can be added that uses just `futhark` and is near-magical in how it deals with the pipeline.
